### ISSUE TITLE
NoSuchMethodError: com.amazonaws.transform.JsonUnmarshallerContext.getCurrentToken()

### ISSUE THREAD

**Issue by gigq** [awslabs/amazon-kinesis-aggregators#3]
From https://forums.aws.amazon.com/thread.jspa?messageID=585971:

Generating Sensor 1
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.transform.JsonUnmarshallerContext.getCurrentToken()Lcom/fasterxml/jackson/core/JsonToken;
at com.amazonaws.services.kinesis.model.transform.PutRecordResultJsonUnmarshaller.unmarshall(PutRecordResultJsonUnmarshaller.java:40)
at com.amazonaws.services.kinesis.model.transform.PutRecordResultJsonUnmarshaller.unmarshall(PutRecordResultJsonUnmarshaller.java:31)
at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:104)
at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:41)
at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:730)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:417)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:245)
at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2326)
at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecord(AmazonKinesisClient.java:557)
at producer.SensorReadingProducer.run(SensorReadingProducer.java:151)
at producer.SensorReadingProducer.main(SensorReadingProducer.java:167)

**Comment by sankarinnoart** [comment]
I am using latest versions of jackson(2.6.3). But it's not working facing the same issue.

**Comment by sankarinnoart** [comment]
Any body having complete java program to access AWS S3 KMS.

**Comment by IanMeyers** [comment]
@sankarinnoart Understood - currently with the way that the AWS SDK talks to Jackson, you have to use the version included in the pom. I am now researching a full update of all the dependencies to see if we can get to the latest version of Jackson.
